server:
  port: '8080'


# Selected Profile
spring:
  profiles:
    active: testing

---

# Profile para Desarrollo
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/alkemy-challenge-dev
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---

# Profile para Testing
spring:
  profiles: testing
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/alkemy-challenge-testing
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

---

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

jwt:
  secret: secretkey123